version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket lambda-build-s3 --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - template.yml
    - packaged-template.yml