AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::903592692848:role/service-role/index-photos-role-cwmlpam1'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  Bucket1:
    Type: 'AWS::S3::Bucket'

  searchlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-lambda
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::903592692848:role/service-role/search-lambda-role-685lgbq8'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
